openapi: 3.0.0
info:
  title: REST activities heartbeat API
  description: The REST API is used for all API interactions with DataCite services.
  contact:
    name: DataCite Support
    url: https://support.datacite.org
    email: support@datacite.org
  license:
    name: MIT
    url: https://raw.githubusercontent.com/datacite/lupo/master/LICENSE
  version: 2.3.0
servers:
- url: https://api.test.datacite.org
  description: Staging server
- url: https://api.datacite.org
  description: Production server
security:
- {}
- BasicAuth: []
- bearerAuth: []
tags:
- name: heartbeat
  description: Heartbeat
paths:
  /heartbeat:
    get:
      tags:
      - heartbeat
      summary: Return the current status of the REST API.
      security: []
      responses:
        '200':
          description: REST API is operating normally.
          content:
            text/plain:
              schema:
                type: string
                example: OK
        '500':
          description: REST API is not working properly.
          content:
            text/plain:
              schema:
                type: string
                example: failed
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
